version: '3.7',

services: 
    postgres: 
        image: postgres
        environment: 
            POSTGRES_DB: nodeauth
            POSTGRES_PASSWORD: postgres
        volumes: 
            - /private/var/lib/postgres:/var/lib/postgres
        ports: 
            - 5432:5432

            # docker system prune -a --volumes
