# docker system prune -a --volumes
version: '3.7'

services: 
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    postgres:
        image: postgres
        environment: 
            POSTGRES_DB: nodeauth
            POSTGRES_PASSWORD: postgres
        volumes: 
            - /private/var/lib/postgres:/var/lib/postgres
        ports: 
            - 5432:5432
